storage: ../storage
auth:
  htpasswd:
    file: ./htpasswd
    max_users: -1
security:
  api:
    jwt:
      sign:
        expiresIn: 7d
      verify:
        algorithms: ['HS256']
uplinks:
  npmjs:
    url: https://registry.npmjs.org/
packages:
  '**':
    access: $all
    publish: $all
    proxy: npmjs
logs:
  - {type: stdout, format: pretty, level: http}